### ISSUE TITLE
Define a standard for describing parameters

### ISSUE THREAD

**Issue by rodber** [chevere/chevere#147]
I need to get an exportable representation for [parameter](https://chevere.org/library/parameter.html) to be used at I/O layers, when browsing the API spec of when issuing a HEAD request.

Inspired on how [Swagger](https://swagger.io/docs/specification/describing-parameters/) describes parameters but focused on my needs and interpretation.

Swagger's:

```yaml
      parameters:
        - in: path
          name: userId
          schema:
            type: integer
          required: true
          description: Numeric ID of the user to get
```

Mine's:

```php
$array = arrayp(
    a: string('^[a-z]{5}$', 'My string'),
)->withOptional(
    b: integer(default: 200, minimum: 100)
);
$export = [
    'a' => [
        'description' => 'My string',
        'required' => true,
        'schema' => [
            'type' => 'string',
            'regex' => '^[a-z]{5}$',
        ],
    ],
    'b' => [
        'description' => '',
        'required' => false,
        'schema' => [
            'type' => 'integer',
            'default' => 200,
            'minimum' => 100,
        ],
    ],
];
```

```yaml
a:
  description: My string
  required: true
  schema:
    type: string
    regex: "^[a-z]{5}$"
b:
  description: ''
  required: false
  schema:
    type: integer
    default: 200
    minimum: 100
```
